@host = http://localhost:8080

### Users Routes Test
POST {{host}}/api/v1/users
Content-Type: application/json

{
    "name": "Ricardo",
    "email": "ricardo@teste.com",
    "password": "12345",
    "role": "admin"
}